### ISSUE TITLE
Stuck in initializing

### ISSUE THREAD

**Issue by tylergroshong** [xtracthub/xtract-crawler#17]
I've been experiencing an issue where the crawl never leaves the initializing stage. Usually, it seems that the first several (5? 7?) times I run a crawl in a day it works, but after I get stuck in an interminable initialization just once I am unable to crawl until the next day or so.

**Comment by tskluzac** [comment]
Added heartbeating to catch 'initializing loop' (for > 30s) and retry. 

Tested on 10 back-to-back crawl invocations on 1000-file CORD subset. Seems to work just fine. 

Thanks for bringing this one to my attention, @tylergroshong. Let me know if you have any more problems with this issue. 

Closing!
